return {
	CONSOLE = {
		docked = true,
		history = {
			"DBG(world.stockpile)",
			"world:SaveWorld()",
			"w = World.LoadWorld(0",
			"w = World.LoadWorld()",
			"world:SaveWorld()",
			"w = World.LoadWorld()",
			"world:SaveWorld()",
			"w = World.LoadWorld()",
			"print(w)",
			"w = World.LoadWorld()",
			"print(w)",
			"DBG(w)",
			"print(screen)",
			"print(screen.world)",
			"print(game.world)",
			"game.world = w",
			"world:SaveWorld()",
			"game.world = World.LoadWorld()",
			"DBG(world.tiles)",
			"DBG(game.world.map.tiles)",
			"print(Shaders)",
			"print(Shaders.foo)",
			"print(game.selected_tile)",
			"print(game.selected_resource)",
			"print(t)",
			"print(t.CollectInteractions)",
			"t = {1,1,1}",
			"print(table.unpack(t))",
			",1print(table.unpack(t))",
			"print(table.unpack(t),1)",
			"print(table.unpack(t,1,3))",
			"print(table.unpack(t,1,3),1)"
		}
	},
	DEBUG_FILE = "debug.lua"
}