return {
	CONSOLE = {
		docked = true,
		history = {
			"print( t:IsFriensd( puppet ))",
			"print( t:IsFriends( puppet ))",
			"print( t:IsAcquainted( puppet ))",
			"t:RegenVerbs()",
			"print(t:IsFriends(puppet))",
			"t:RegenVerbs()",
			"print(t:IsFriends(puppet))",
			"print(t:CalculateTimeSpeed())",
			"print(t:GetWorld())",
			"print(t.owner)",
			"print(Trait)",
			"print(Trait.OnSpawn, Aspect.OnSpawn)",
			"print(t:IsWorking())",
			"print(t:IsTimeForShift())",
			"print(t:IsDoing())",
			"print(t:IsWorking())",
			"print(t:GetLocation())",
			"print(debug_world_speed)",
			"print( DEFAULT_DEBUG_SPEED )",
			"print(debug_world_speed)",
			"print(DEBUG_WORLD_SPEEDS[ debug_world_speed ] )",
			"print( math.modf(2.3))",
			"print( math.modf(2.3, 1.0))",
			"print( math.modf(2.3, 551.0))",
			"print(world:CalculateTimeElapsed(1.0))",
			"print( math.modf(2.3, 551.0))",
			"print(world:CalculateTimeElapsed(1.0))",
			"print(world.debug_world_speed)",
			"print(world:CalculateTimeElapsed(1.0))",
			"print( Verb.Attack )",
			"t:EvaluateTargets()",
			"sdf"
		}
	},
	DEBUG_FILE = "debug.lua"
}